name: red_sequence_evolution

channels:
  - defaults

dependencies:
    - python>=3.6
    - ipython
    - anaconda
    - astropy
    - h5py
    - numpy
    - pandas
    - scipy
    - seaborn
    - sphinx >= 1.6
    - pip>=10.0
    - pip:
        - GitPython
        - progressbar2
        - cosmo-utils
        - configparser
        - sphinx-astropy
        - sphinx_rtd_theme
        - tables
        - tqdm
        - git+https://github.com/mfouesneau/tap
        - easyaccess==1.4.5
